#!/bin/sh
if [ -z $1 ]; then 
  exit 1
fi

if [[ $1 == all ]]; then
  (sleep 3; open -a "Firefox Developer Edition" http://localhost:8000) &
  python -m SimpleHTTPServer 8000
  exit 1
fi

if [[ $1 =~ .*\.js ]]; then
  node $1
  exit 1
fi

if [[ $1 =~ .*\.html ]]; then
  open -a "Firefox Developer Edition" $1
  exit 1
fi
