#!/bin/sh
browser="Firefox Developer Edition"
url="http://localhost:"
port="8000"

if [ -z $1 ]; then 
  exit 1
fi

if [[ $1 == all ]]; then
  (sleep 3; open -a "$browser" $url$port) &
  python -m SimpleHTTPServer $port
  exit 1
fi

if [[ $1 =~ .*\.js ]]; then
  node $1
  exit 1
fi

if [[ $1 =~ .*\.html ]]; then
  open -a "$browser" $1
  exit 1
fi
