#!/bin/sh
if [ -z $1 ]; then 
  exit 1
fi

if [[ $1 == all ]]; then
  python -m SimpleHTTPServer 8000 &
  open -a firefox http://localhost:8000
  exit 1
fi

if [[ $1 =~ .*\.js ]]; then
  node $1
  exit 1
fi

if [[ $1 =~ .*\.html ]]; then
  open -a firefox $1
  exit 1
fi


